#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : hdf5
Version  : 1.8.19
Release  : 8
URL      : https://support.hdfgroup.org/ftp/HDF5/current18/src/hdf5-1.8.19.tar.gz
Source0  : https://support.hdfgroup.org/ftp/HDF5/current18/src/hdf5-1.8.19.tar.gz
Summary  : HDF5 is a unique technology suite that makes possible the management of extremely large and complex data collections.
Group    : Development/Tools
License  : BSD-4-Clause-UC
Requires: hdf5-bin
Requires: hdf5-lib
Requires: hdf5-data
BuildRequires : cmake
BuildRequires : zlib-dev

%description
h5repack_nested_8bit_enum_deflated.h5:
h5repack_nested_8bit_enum.h5:
enuberated 8bit type nested in compount type.  Original file provided
by a user (HDFFV-8667) as a test file. Used h5copy to extract only the
Compound type dataset. The non-deflated version is produced by h5repack.

%package bin
Summary: bin components for the hdf5 package.
Group: Binaries
Requires: hdf5-data

%description bin
bin components for the hdf5 package.


%package data
Summary: data components for the hdf5 package.
Group: Data

%description data
data components for the hdf5 package.


%package dev
Summary: dev components for the hdf5 package.
Group: Development
Requires: hdf5-lib
Requires: hdf5-bin
Requires: hdf5-data
Provides: hdf5-devel

%description dev
dev components for the hdf5 package.


%package lib
Summary: lib components for the hdf5 package.
Group: Libraries
Requires: hdf5-data

%description lib
lib components for the hdf5 package.


%prep
%setup -q -n hdf5-1.8.19

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1505678043
export CFLAGS="$CFLAGS -O3 -falign-functions=32 -fno-common -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export FCFLAGS="$CFLAGS -O3 -falign-functions=32 -fno-common -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export FFLAGS="$CFLAGS -O3 -falign-functions=32 -fno-common -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export CXXFLAGS="$CXXFLAGS -O3 -falign-functions=32 -fno-common -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
%configure --disable-static --enable-cxx --enable-fortran
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1505678043
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)
/usr/lib64/libhdf5.settings

%files bin
%defattr(-,root,root,-)
/usr/bin/gif2h5
/usr/bin/h52gif
/usr/bin/h5c++
/usr/bin/h5cc
/usr/bin/h5copy
/usr/bin/h5debug
/usr/bin/h5diff
/usr/bin/h5dump
/usr/bin/h5fc
/usr/bin/h5import
/usr/bin/h5jam
/usr/bin/h5ls
/usr/bin/h5mkgrp
/usr/bin/h5perf_serial
/usr/bin/h5redeploy
/usr/bin/h5repack
/usr/bin/h5repart
/usr/bin/h5stat
/usr/bin/h5unjam

%files data
%defattr(-,root,root,-)
/usr/share/hdf5_examples/README
/usr/share/hdf5_examples/c++/chunks.cpp
/usr/share/hdf5_examples/c++/compound.cpp
/usr/share/hdf5_examples/c++/create.cpp
/usr/share/hdf5_examples/c++/extend_ds.cpp
/usr/share/hdf5_examples/c++/h5group.cpp
/usr/share/hdf5_examples/c++/h5tutr_cmprss.cpp
/usr/share/hdf5_examples/c++/h5tutr_crtatt.cpp
/usr/share/hdf5_examples/c++/h5tutr_crtdat.cpp
/usr/share/hdf5_examples/c++/h5tutr_crtgrp.cpp
/usr/share/hdf5_examples/c++/h5tutr_crtgrpar.cpp
/usr/share/hdf5_examples/c++/h5tutr_crtgrpd.cpp
/usr/share/hdf5_examples/c++/h5tutr_extend.cpp
/usr/share/hdf5_examples/c++/h5tutr_rdwt.cpp
/usr/share/hdf5_examples/c++/h5tutr_subset.cpp
/usr/share/hdf5_examples/c++/readdata.cpp
/usr/share/hdf5_examples/c++/run-c++-ex.sh
/usr/share/hdf5_examples/c++/writedata.cpp
/usr/share/hdf5_examples/c/h5_attribute.c
/usr/share/hdf5_examples/c/h5_chunk_read.c
/usr/share/hdf5_examples/c/h5_cmprss.c
/usr/share/hdf5_examples/c/h5_compound.c
/usr/share/hdf5_examples/c/h5_crtatt.c
/usr/share/hdf5_examples/c/h5_crtdat.c
/usr/share/hdf5_examples/c/h5_crtgrp.c
/usr/share/hdf5_examples/c/h5_crtgrpar.c
/usr/share/hdf5_examples/c/h5_crtgrpd.c
/usr/share/hdf5_examples/c/h5_drivers.c
/usr/share/hdf5_examples/c/h5_elink_unix2win.c
/usr/share/hdf5_examples/c/h5_extend.c
/usr/share/hdf5_examples/c/h5_extend_write.c
/usr/share/hdf5_examples/c/h5_extlink.c
/usr/share/hdf5_examples/c/h5_group.c
/usr/share/hdf5_examples/c/h5_mount.c
/usr/share/hdf5_examples/c/h5_rdwt.c
/usr/share/hdf5_examples/c/h5_read.c
/usr/share/hdf5_examples/c/h5_ref2reg.c
/usr/share/hdf5_examples/c/h5_reference.c
/usr/share/hdf5_examples/c/h5_select.c
/usr/share/hdf5_examples/c/h5_shared_mesg.c
/usr/share/hdf5_examples/c/h5_subset.c
/usr/share/hdf5_examples/c/h5_write.c
/usr/share/hdf5_examples/c/ph5example.c
/usr/share/hdf5_examples/c/run-c-ex.sh
/usr/share/hdf5_examples/fortran/compound.f90
/usr/share/hdf5_examples/fortran/h5_cmprss.f90
/usr/share/hdf5_examples/fortran/h5_crtatt.f90
/usr/share/hdf5_examples/fortran/h5_crtdat.f90
/usr/share/hdf5_examples/fortran/h5_crtgrp.f90
/usr/share/hdf5_examples/fortran/h5_crtgrpar.f90
/usr/share/hdf5_examples/fortran/h5_crtgrpd.f90
/usr/share/hdf5_examples/fortran/h5_extend.f90
/usr/share/hdf5_examples/fortran/h5_rdwt.f90
/usr/share/hdf5_examples/fortran/h5_subset.f90
/usr/share/hdf5_examples/fortran/hyperslab.f90
/usr/share/hdf5_examples/fortran/mountexample.f90
/usr/share/hdf5_examples/fortran/ph5example.f90
/usr/share/hdf5_examples/fortran/refobjexample.f90
/usr/share/hdf5_examples/fortran/refregexample.f90
/usr/share/hdf5_examples/fortran/run-fortran-ex.sh
/usr/share/hdf5_examples/fortran/selectele.f90
/usr/share/hdf5_examples/hl/c++/ptExampleFL.cpp
/usr/share/hdf5_examples/hl/c++/run-hlc++-ex.sh
/usr/share/hdf5_examples/hl/c/ex_ds1.c
/usr/share/hdf5_examples/hl/c/ex_image1.c
/usr/share/hdf5_examples/hl/c/ex_image2.c
/usr/share/hdf5_examples/hl/c/ex_lite1.c
/usr/share/hdf5_examples/hl/c/ex_lite2.c
/usr/share/hdf5_examples/hl/c/ex_lite3.c
/usr/share/hdf5_examples/hl/c/ex_table_01.c
/usr/share/hdf5_examples/hl/c/ex_table_02.c
/usr/share/hdf5_examples/hl/c/ex_table_03.c
/usr/share/hdf5_examples/hl/c/ex_table_04.c
/usr/share/hdf5_examples/hl/c/ex_table_05.c
/usr/share/hdf5_examples/hl/c/ex_table_06.c
/usr/share/hdf5_examples/hl/c/ex_table_07.c
/usr/share/hdf5_examples/hl/c/ex_table_08.c
/usr/share/hdf5_examples/hl/c/ex_table_09.c
/usr/share/hdf5_examples/hl/c/ex_table_10.c
/usr/share/hdf5_examples/hl/c/ex_table_11.c
/usr/share/hdf5_examples/hl/c/ex_table_12.c
/usr/share/hdf5_examples/hl/c/image24pixel.txt
/usr/share/hdf5_examples/hl/c/image8.txt
/usr/share/hdf5_examples/hl/c/pal_rgb.h
/usr/share/hdf5_examples/hl/c/ptExampleFL.c
/usr/share/hdf5_examples/hl/c/run-hlc-ex.sh
/usr/share/hdf5_examples/hl/fortran/ex_ds1.f90
/usr/share/hdf5_examples/hl/fortran/exlite.f90
/usr/share/hdf5_examples/hl/fortran/run-hlfortran-ex.sh
/usr/share/hdf5_examples/hl/run-hl-ex.sh
/usr/share/hdf5_examples/run-all-ex.sh

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/include/h5_dble_interface.mod
/usr/include/h5a.mod
/usr/include/h5a_provisional.mod
/usr/include/h5d.mod
/usr/include/h5d_provisional.mod
/usr/include/h5ds.mod
/usr/include/h5e.mod
/usr/include/h5e_provisional.mod
/usr/include/h5f.mod
/usr/include/h5f_provisional.mod
/usr/include/h5fortran_types.mod
/usr/include/h5g.mod
/usr/include/h5global.mod
/usr/include/h5i.mod
/usr/include/h5im.mod
/usr/include/h5l.mod
/usr/include/h5l_provisional.mod
/usr/include/h5lib.mod
/usr/include/h5lib_provisional.mod
/usr/include/h5lt.mod
/usr/include/h5o.mod
/usr/include/h5o_provisional.mod
/usr/include/h5p.mod
/usr/include/h5p_provisional.mod
/usr/include/h5r.mod
/usr/include/h5r_provisional.mod
/usr/include/h5s.mod
/usr/include/h5t.mod
/usr/include/h5t_provisional.mod
/usr/include/h5tb.mod
/usr/include/h5test_kind_storage_size_mod.mod
/usr/include/h5z.mod
/usr/include/hdf5.mod
/usr/lib64/libhdf5.so
/usr/lib64/libhdf5_cpp.so
/usr/lib64/libhdf5_fortran.so
/usr/lib64/libhdf5_hl.so
/usr/lib64/libhdf5_hl_cpp.so
/usr/lib64/libhdf5hl_fortran.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/libhdf5.so.10
/usr/lib64/libhdf5.so.10.3.0
/usr/lib64/libhdf5_cpp.so.14
/usr/lib64/libhdf5_cpp.so.14.0.0
/usr/lib64/libhdf5_fortran.so.10
/usr/lib64/libhdf5_fortran.so.10.0.4
/usr/lib64/libhdf5_hl.so.10
/usr/lib64/libhdf5_hl.so.10.2.0
/usr/lib64/libhdf5_hl_cpp.so.11
/usr/lib64/libhdf5_hl_cpp.so.11.1.0
/usr/lib64/libhdf5hl_fortran.so.10
/usr/lib64/libhdf5hl_fortran.so.10.0.3
