#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
%define keepstatic 1
Name     : hdf5
Version  : 1.12.1
Release  : 312
URL      : https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.12/hdf5-1.12.1/src/hdf5-1.12.1.tar.bz2
Source0  : https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.12/hdf5-1.12.1/src/hdf5-1.12.1.tar.bz2
Summary  : HDF5 (Hierarchical Data Format 5) Software Library
Group    : Development/Tools
License  : GPL-2.0
Requires: hdf5-bin = %{version}-%{release}
Requires: hdf5-lib = %{version}-%{release}
BuildRequires : automake
BuildRequires : automake-dev
BuildRequires : binutils-dev
BuildRequires : buildreq-cmake
BuildRequires : buildreq-configure
BuildRequires : doxygen
BuildRequires : elfutils-dev
BuildRequires : gcc
BuildRequires : gcc-dev
BuildRequires : gcc-libs-math
BuildRequires : gcc-libstdc++32
BuildRequires : gcc-libubsan
BuildRequires : gcc-locale
BuildRequires : gfortran
BuildRequires : glibc-dev
BuildRequires : glibc-staticdev
BuildRequires : libedit
BuildRequires : libedit-dev
BuildRequires : libffi-dev
BuildRequires : libffi-staticdev
BuildRequires : libgcc1
BuildRequires : libstdc++
BuildRequires : libxml2-dev
BuildRequires : libxml2-staticdev
BuildRequires : m4
BuildRequires : modules
BuildRequires : ncurses-dev
BuildRequires : openmpi
BuildRequires : openmpi-dev
BuildRequires : openssh
BuildRequires : python3-dev
BuildRequires : python3-staticdev
BuildRequires : xz-dev
BuildRequires : xz-staticdev
BuildRequires : zlib-dev
BuildRequires : zlib-staticdev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
===================================
===================================
This directory contains Fortran APIs for HDF5 Library functionality.
A complete list of implemented Fortran subroutines can be found in the HDF5
Reference Manual.

%package bin
Summary: bin components for the hdf5 package.
Group: Binaries

%description bin
bin components for the hdf5 package.


%package dev
Summary: dev components for the hdf5 package.
Group: Development
Requires: hdf5-lib = %{version}-%{release}
Requires: hdf5-bin = %{version}-%{release}
Provides: hdf5-devel = %{version}-%{release}
Requires: hdf5 = %{version}-%{release}

%description dev
dev components for the hdf5 package.


%package lib
Summary: lib components for the hdf5 package.
Group: Libraries

%description lib
lib components for the hdf5 package.


%package staticdev
Summary: staticdev components for the hdf5 package.
Group: Default
Requires: hdf5-dev = %{version}-%{release}

%description staticdev
staticdev components for the hdf5 package.


%prep
%setup -q -n hdf5-1.12.1
cd %{_builddir}/hdf5-1.12.1

%build
unset http_proxy
unset https_proxy
unset no_proxy
export SSL_CERT_FILE=/var/cache/ca-certs/anchors/ca-certificates.crt
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1627511843
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
## altflags1 content
export CFLAGS="-g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -mprefer-vector-width=256 -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc -Wl,--build-id=sha1"
## -fno-tree-vectorize: disable -ftree-vectorize thus disable -ftree-loop-vectorize and -ftree-slp-vectorize
## -Ofast -ffast-math
## -funroll-loops maybe dangerous
## -Wl,-z,max-page-size=0x1000
export CXXFLAGS="-g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -mprefer-vector-width=256 -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -fvisibility-inlines-hidden -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc -Wl,--build-id=sha1"
#
export FCFLAGS="-g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -mprefer-vector-width=256 -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc -Wl,--build-id=sha1"
export FFLAGS="-g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -mprefer-vector-width=256 -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -Wl,--build-id=sha1"
export CFFLAGS="-g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -mprefer-vector-width=256 -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc -Wl,--build-id=sha1"
#
export LDFLAGS="-g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -mprefer-vector-width=256 -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc -lpthread -Wl,--build-id=sha1"
#
export AR=/usr/bin/gcc-ar
export RANLIB=/usr/bin/gcc-ranlib
export NM=/usr/bin/gcc-nm
#
export MAKEFLAGS=%{?_smp_mflags}
#
%global _lto_cflags 1
#global _lto_cflags %{nil}
%global _disable_maintainer_mode 1
#%global _disable_maintainer_mode %{nil}
#
export CCACHE_DISABLE=true
export CCACHE_NOHASHDIR=true
export CCACHE_CPP2=true
export CCACHE_SLOPPINESS=pch_defines,time_macros,locale,file_stat_matches,file_stat_matches_ctime,include_file_ctime,include_file_mtime,modules,system_headers,clang_index_store,file_macro
#export CCACHE_SLOPPINESS=modules,include_file_mtime,include_file_ctime,time_macros,pch_defines,file_stat_matches,clang_index_store,system_headers,locale
#export CCACHE_SLOPPINESS=pch_defines,time_macros,locale,clang_index_store,file_macro
export CCACHE_DIR=/var/tmp/ccache
export CCACHE_BASEDIR=/builddir/build/BUILD
#export CCACHE_LOGFILE=/var/tmp/ccache/cache.debug
#export CCACHE_DEBUG=true
#export CCACHE_NODIRECT=true
#
export LD_LIBRARY_PATH="/usr/nvidia/lib64:/usr/nvidia/lib64/vdpau:/usr/nvidia/lib64/xorg/modules/drivers:/usr/nvidia/lib64/xorg/modules/extensions:/usr/local/cuda/lib64:/usr/lib64/haswell:/usr/lib64/dri:/usr/lib64/chromium:/usr/lib64:/usr/lib64/pulseaudio:/usr/lib64/alsa-lib:/usr/lib64/gstreamer-1.0:/usr/lib64/pipewire-0.3:/usr/lib64/spa-0.2:/usr/lib:/aot/intel/oneapi/compiler/latest/linux/compiler/lib/intel64_lin:/aot/intel/oneapi/compiler/latest/linux/lib:/aot/intel/oneapi/mkl/latest/lib/intel64:/aot/intel/oneapi/tbb/latest/lib/intel64/gcc4.8:/usr/share:/usr/lib64/wine:/usr/nvidia/lib32:/usr/nvidia/lib32/vdpau:/usr/lib32:/usr/lib32/wine"
#
export LIBRARY_PATH="/usr/nvidia/lib64:/usr/nvidia/lib64/vdpau:/usr/nvidia/lib64/xorg/modules/drivers:/usr/nvidia/lib64/xorg/modules/extensions:/usr/local/cuda/lib64:/usr/lib64/haswell:/usr/lib64/dri:/usr/lib64/chromium:/usr/lib64:/usr/lib64/pulseaudio:/usr/lib64/alsa-lib:/usr/lib64/gstreamer-1.0:/usr/lib64/pipewire-0.3:/usr/lib64/spa-0.2:/usr/lib:/aot/intel/oneapi/compiler/latest/linux/compiler/lib/intel64_lin:/aot/intel/oneapi/compiler/latest/linux/lib:/aot/intel/oneapi/mkl/latest/lib/intel64:/aot/intel/oneapi/tbb/latest/lib/intel64/gcc4.8:/usr/share:/usr/lib64/wine:/usr/nvidia/lib32:/usr/nvidia/lib32/vdpau:/usr/lib32:/usr/lib32/wine"
#
export PATH="/usr/lib64/ccache/bin:/usr/local/cuda/bin:/usr/nvidia/bin:/usr/bin/haswell:/usr/bin:/usr/sbin"
#
export CPATH="/usr/local/cuda/include"
#
export DISPLAY=:0
export __GL_ALLOW_UNOFFICIAL_PROTOCOL=1
export __GL_SYNC_TO_VBLANK=0
export __GL_SYNC_DISPLAY_DEVICE=DFP-1
export VDPAU_NVIDIA_SYNC_DISPLAY_DEVICE=DFP-1
export LANG=en_US.UTF-8
export XDG_CONFIG_DIRS=/usr/share/xdg:/etc/xdg
export XDG_SEAT=seat0
export XDG_SESSION_TYPE=tty
export XDG_CURRENT_DESKTOP=KDE
export XDG_SESSION_CLASS=user
export XDG_VTNR=1
export XDG_SESSION_ID=1
export XDG_RUNTIME_DIR=/run/user/1000
export XDG_DATA_DIRS=/usr/local/share:/usr/share
export KDE_SESSION_VERSION=5
export KDE_SESSION_UID=1000
export KDE_FULL_SESSION=true
export KDE_APPLICATIONS_AS_SCOPE=1
export VDPAU_DRIVER=nvidia
export LIBVA_DRIVER_NAME=vdpau
export LIBVA_DRIVERS_PATH=/usr/lib64/dri
export GTK_RC_FILES=/etc/gtk/gtkrc
export FONTCONFIG_PATH=/usr/share/defaults/fonts
## altflags1 end
%configure --enable-cxx --enable-fortran --enable-static --enable-shared --enable-optimization=high --enable-static-exec --enable-build-mode=production --enable-tools --enable-tests=no --disable-tests
## make_prepend content
#sd "uninstall-examples" "install" $(fd -uu --glob Makefile)
sd "install-examples" "" $(fd -uu --glob Makefile)
## make_prepend end
make  %{?_smp_mflags}    V=1 VERBOSE=1


%install
export SOURCE_DATE_EPOCH=1627511843
rm -rf %{buildroot}
%make_install
## install_append content
install -dm 0755 %{buildroot}/usr/lib64/haswell/ || :
cp --archive %{buildroot}/usr/lib64/lib*.so* %{buildroot}/usr/lib64/haswell/ || :
## install_append end

%files
%defattr(-,root,root,-)
/usr/lib64/libhdf5.settings

%files bin
%defattr(-,root,root,-)
/usr/bin/gif2h5
/usr/bin/h52gif
/usr/bin/h5c++
/usr/bin/h5cc
/usr/bin/h5clear
/usr/bin/h5copy
/usr/bin/h5debug
/usr/bin/h5diff
/usr/bin/h5dump
/usr/bin/h5fc
/usr/bin/h5format_convert
/usr/bin/h5import
/usr/bin/h5jam
/usr/bin/h5ls
/usr/bin/h5mkgrp
/usr/bin/h5redeploy
/usr/bin/h5repack
/usr/bin/h5repart
/usr/bin/h5stat
/usr/bin/h5unjam
/usr/bin/h5watch
/usr/bin/mirror_server
/usr/bin/mirror_server_stop

%files dev
%defattr(-,root,root,-)
/usr/include/H5ACpublic.h
/usr/include/H5AbstractDs.h
/usr/include/H5Apublic.h
/usr/include/H5ArrayType.h
/usr/include/H5AtomType.h
/usr/include/H5Attribute.h
/usr/include/H5Classes.h
/usr/include/H5CommonFG.h
/usr/include/H5CompType.h
/usr/include/H5Cpp.h
/usr/include/H5CppDoc.h
/usr/include/H5Cpublic.h
/usr/include/H5DOpublic.h
/usr/include/H5DSpublic.h
/usr/include/H5DaccProp.h
/usr/include/H5DataSet.h
/usr/include/H5DataSpace.h
/usr/include/H5DataType.h
/usr/include/H5DcreatProp.h
/usr/include/H5Dpublic.h
/usr/include/H5DxferProp.h
/usr/include/H5ESpublic.h
/usr/include/H5EnumType.h
/usr/include/H5Epubgen.h
/usr/include/H5Epublic.h
/usr/include/H5Exception.h
/usr/include/H5FDcore.h
/usr/include/H5FDdirect.h
/usr/include/H5FDfamily.h
/usr/include/H5FDhdfs.h
/usr/include/H5FDlog.h
/usr/include/H5FDmirror.h
/usr/include/H5FDmpi.h
/usr/include/H5FDmpio.h
/usr/include/H5FDmulti.h
/usr/include/H5FDpublic.h
/usr/include/H5FDros3.h
/usr/include/H5FDsec2.h
/usr/include/H5FDsplitter.h
/usr/include/H5FDstdio.h
/usr/include/H5FDwindows.h
/usr/include/H5FaccProp.h
/usr/include/H5FcreatProp.h
/usr/include/H5File.h
/usr/include/H5FloatType.h
/usr/include/H5Fpublic.h
/usr/include/H5Gpublic.h
/usr/include/H5Group.h
/usr/include/H5IMpublic.h
/usr/include/H5IdComponent.h
/usr/include/H5Include.h
/usr/include/H5IntType.h
/usr/include/H5Ipublic.h
/usr/include/H5LDpublic.h
/usr/include/H5LTpublic.h
/usr/include/H5LaccProp.h
/usr/include/H5LcreatProp.h
/usr/include/H5Library.h
/usr/include/H5Location.h
/usr/include/H5Lpublic.h
/usr/include/H5MMpublic.h
/usr/include/H5Mpublic.h
/usr/include/H5Object.h
/usr/include/H5OcreatProp.h
/usr/include/H5Opublic.h
/usr/include/H5PLextern.h
/usr/include/H5PLpublic.h
/usr/include/H5PTpublic.h
/usr/include/H5PacketTable.h
/usr/include/H5Ppublic.h
/usr/include/H5PredType.h
/usr/include/H5PropList.h
/usr/include/H5Rpublic.h
/usr/include/H5Spublic.h
/usr/include/H5StrType.h
/usr/include/H5TBpublic.h
/usr/include/H5Tpublic.h
/usr/include/H5VLconnector.h
/usr/include/H5VLconnector_passthru.h
/usr/include/H5VLnative.h
/usr/include/H5VLpassthru.h
/usr/include/H5VLpublic.h
/usr/include/H5VarLenType.h
/usr/include/H5Zpublic.h
/usr/include/H5api_adpt.h
/usr/include/H5f90i.h
/usr/include/H5f90i_gen.h
/usr/include/H5overflow.h
/usr/include/H5pubconf.h
/usr/include/H5public.h
/usr/include/H5version.h
/usr/include/h5_gen.mod
/usr/include/h5a.mod
/usr/include/h5d.mod
/usr/include/h5ds.mod
/usr/include/h5e.mod
/usr/include/h5f.mod
/usr/include/h5fortkit.mod
/usr/include/h5fortran_types.mod
/usr/include/h5g.mod
/usr/include/h5global.mod
/usr/include/h5i.mod
/usr/include/h5im.mod
/usr/include/h5l.mod
/usr/include/h5lib.mod
/usr/include/h5lt.mod
/usr/include/h5lt_const.mod
/usr/include/h5o.mod
/usr/include/h5p.mod
/usr/include/h5r.mod
/usr/include/h5s.mod
/usr/include/h5t.mod
/usr/include/h5tb.mod
/usr/include/h5tb_const.mod
/usr/include/h5vl.mod
/usr/include/h5z.mod
/usr/include/hdf5.h
/usr/include/hdf5.mod
/usr/include/hdf5_hl.h
/usr/lib64/haswell/libhdf5.so
/usr/lib64/haswell/libhdf5_cpp.so
/usr/lib64/haswell/libhdf5_fortran.so
/usr/lib64/haswell/libhdf5_hl.so
/usr/lib64/haswell/libhdf5_hl_fortran.so
/usr/lib64/haswell/libhdf5hl_fortran.so
/usr/lib64/libhdf5.so
/usr/lib64/libhdf5_cpp.so
/usr/lib64/libhdf5_fortran.so
/usr/lib64/libhdf5_hl.so
/usr/lib64/libhdf5_hl_cpp.so
/usr/lib64/libhdf5_hl_fortran.so
/usr/lib64/libhdf5hl_fortran.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/haswell/libhdf5.so.200
/usr/lib64/haswell/libhdf5.so.200.1.0
/usr/lib64/haswell/libhdf5_cpp.so.200
/usr/lib64/haswell/libhdf5_cpp.so.200.1.0
/usr/lib64/haswell/libhdf5_fortran.so.200
/usr/lib64/haswell/libhdf5_fortran.so.200.1.0
/usr/lib64/haswell/libhdf5_hl.so.200
/usr/lib64/haswell/libhdf5_hl.so.200.0.1
/usr/lib64/haswell/libhdf5hl_fortran.so.200
/usr/lib64/haswell/libhdf5hl_fortran.so.200.0.1
/usr/lib64/libhdf5.so.200
/usr/lib64/libhdf5.so.200.1.0
/usr/lib64/libhdf5_cpp.so.200
/usr/lib64/libhdf5_cpp.so.200.1.0
/usr/lib64/libhdf5_fortran.so.200
/usr/lib64/libhdf5_fortran.so.200.1.0
/usr/lib64/libhdf5_hl.so.200
/usr/lib64/libhdf5_hl.so.200.0.1
/usr/lib64/libhdf5_hl_cpp.so.200
/usr/lib64/libhdf5_hl_cpp.so.200.0.1
/usr/lib64/libhdf5hl_fortran.so.200
/usr/lib64/libhdf5hl_fortran.so.200.0.1

%files staticdev
%defattr(-,root,root,-)
/usr/lib64/libhdf5.a
/usr/lib64/libhdf5_cpp.a
/usr/lib64/libhdf5_fortran.a
/usr/lib64/libhdf5_hl.a
/usr/lib64/libhdf5_hl_cpp.a
/usr/lib64/libhdf5_hl_fortran.a
/usr/lib64/libhdf5hl_fortran.a
